version: 0.2
phases:
 install:
   runtime-versions:
     java: corretto17
 pre_build:
   commands:
     - echo "Installing Maven..."
     - apt-get update -y
     - apt-get install -y maven
 build:
   commands:
     - echo "Building the Java application..."
     - mvn clean install package
 post_build:
   commands:
     - echo "Build completed."
     - echo "Running the Java application..."
     - java -jar target/spring-boot-web.jar
artifacts:
 files:
   - '**/*' 
 
