version: 0.2

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - 'target/*.war'  # Include the .war file in the artifacts
    - 'scripts/*'      # Optionally, include any necessary scripts
  discard-paths: yes   # Store files without maintaining directory structure

post_build:
  commands:
    - echo Creating zip file...
    - cd target && zip -r myapp.zip *.war
    - mv myapp.zip ../myapp.zip  # Move the zip file to the root directory
