version: 0.1

phases:
  install:
    commands:
      - echo installing Maven...
      - yum install -y maven

  build:
    commands:
      - echo Build started on `date`
      - mvn clean test package

artifacts:
  files:
    - target/*.war
