version: 0.0
os: linux
files:
 - source: /spring-boot-web.jar
  destination: /tmp
hooks:
 ApplicationStop:
  - location: scripts/stop_server.sh
    timeout: 30
    runas: root
 ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 30
    runas: root
